import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../Components/Navbar/Navbar.jsx'
import styles from '../styles/Home.module.css'
import  { List } from '../Components/List'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tax adda assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar href={'/addInvoice'} routeName={'Add Invoice'}/>
       <div className={styles.List}>
        <h1>Invoice List</h1>
        <List/>
       </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
